### ISSUE TITLE
Puste bloki

### ISSUE THREAD

**Issue by lazydevelopers** [dbsupport/dbs-reports-issues#17]
Jesli OZNACZONY blok jest "pusty" - czyli zawiera same białe znaki (dla rtf będą to też znaczniki) to NIE generuj zawartości bloku.

**Comment by dbsupport** [comment]
This issue was moved to dbsupport/dbs-reports#72

**Comment by dbsupport** [comment]
This issue was moved to dbsupport/dbs-reports#74
