### ISSUE TITLE
profil HR: LIUTIL

### ISSUE THREAD

**Issue by lazydevelopers** [dbsupport/dbs-reports-issues#3]
dodatkowe pole _opis_ (LIUTIL) z HR (ktore nie bedzie wprowadzane przy nowym profilu), pole NIE edytowalne, pokazuje sie przy detalach profilu (zamiast imie/nazwisko)

niepotrzebne rozbicie LIUTIL na imie/nazwisko-> wrzucic to do _opis_

**Comment by dbsupport** [comment]
This issue was moved to dbsupport/dbs-reports#88
