### ISSUE TITLE
Po generacji przejście od razu do listy "Twoje raporty"

### ISSUE THREAD

**Issue by lazydevelopers** [dbsupport/dbs-reports-issues#37]
"Uruchamiam generację - mam widok Zakończenie generacji raportu i listę Zlecone raporty (dlaczego Zakończenie? To jest niespójne), czekam na wykonanie - dostaje info na belce, 
lista nie odświeża się (wisi zlecony i nic tam nie można zrobić, to też jest mylące bo użytkownik będzie myślał że tam się odświeży i pokaże, że gotowe)."

Czyli po generacji przejście od razu na listę "Twoje raporty"

**Comment by dbsupport** [comment]
This issue was moved to dbsupport/dbs-reports#56
