### ISSUE TITLE
Odświeżanie listy "Twoje raporty" po zdarzeniu wygenerowania raportu.

### ISSUE THREAD

**Issue by lazydevelopers** [dbsupport/dbs-reports-issues#39]
"Dopiero po wcisnięciu info z belki wchodzi w niezarchiwizowane raporty i pokazuje ten jeden jako gotowy (i błędny bo mamy pusty parametr) - czy może sie to odświerzyć po wykonaniu? I od razu pokazać zlecony na liście Twoje raporty?"

**Comment by dbsupport** [comment]
This issue was moved to dbsupport/dbs-reports#54
