### ISSUE TITLE
synchronizacja

### ISSUE THREAD

**Issue by lazydevelopers** [dbsupport/dbs-reports-issues#4]
- profil jest w HR i 
  ++ NIE istnieje w bazie lokalnej -> dopisz do bazy lokalnej
  ++ istnieje w stanie NIEAKTYWNYM/USUNIETY (active=0) -> nic
  ++ istnieje w stanie AKTYWNYM (active=1) -> aktualizuj pole _opis_
- profil NIE istnieje w HR i
  ++ istnieje w bazie lokalnej w stanie NIEAKTYWNY/USUNIETY -> nic
  ++ istnieje w bazie lokalnej w stanie AKTYWNY -> dezaktywacja (usuniecie)
  ++ NIE istnieje w bazie lokalnej -> nic
- profil stworzony lokalnie, taki sam (ten sam login) przychodzi z HR -> nic
- kazdy zaciagniety nowy z HR powinien miec USera

**Comment by dbsupport** [comment]
This issue was moved to dbsupport/dbs-reports#87
