### ISSUE TITLE
JPA level logging

### ISSUE THREAD

**Issue by lazydevelopers** [dbsupport/dbs-reports-issues#53]
Zmniejszyć poziom logowania przez JPA (pro): persistence.xml:

property name="eclipselink.logging.level" value="INFO"/>
property name="eclipselink.logging.level.sql" value="INFO"/>
property name="eclipselink.logging.parameters" value="true"/>
property name="eclipselink.logging.logger" value="ServerLogger"/>

**Comment by dbsupport** [comment]
This issue was moved to dbsupport/dbs-reports#40
