### ISSUE TITLE
Dziury w DB

### ISSUE THREAD

**Issue by lazydevelopers** [dbsupport/dbs-reports-issues#66]
Brakuje FK:

ALTER TABLE reports.tre_order_report
ADD CONSTRAINT "FKRE_ORDER_REPORT"
FOREIGN KEY (report_id) REFERENCES tre_report(id);

Dlaczego?

**Comment by lazydevelopers** [comment]
Liquidbase

**Comment by dbsupport** [comment]
This issue was moved to dbsupport/dbs-reports#27
