### ISSUE TITLE
Podczas zapisywania logów przy generacji raportu zwiększyć dokładność czasu

### ISSUE THREAD

**Issue by lazydevelopers** [dbsupport/dbs-reports-issues#70]
Podczas zapisywania logów przy generacji raportu zwiększyć dokładność czasu do milisekund tak by sortowanie miało sens dla operacji przebiegających w 1 sekundzie.

**Comment by lazydevelopers** [comment]
FORMAT dd.MM.yyyy HH:mm:ss.SSS

**Comment by dbsupport** [comment]
This issue was moved to dbsupport/dbs-reports#23
