### ISSUE TITLE
Umożliwić wykonywanie zapytań "klienckich" na bazie PostgreSQL

### ISSUE THREAD

**Issue by lazydevelopers** [dbsupport/dbs-reports-issues#71]
Zweryfikować możliwość wykonywania zapytań do innej bazy PostgreSQL (nie do Oracle).
Jeśli wymagane - zaimplementować nowy moduł (implementacja API).

**Comment by lazydevelopers** [comment]
- URL database parameter
- INFLATER_PATTERN (\w+):\s*(SELECT\s+.+?[FROM]{0,1}\s+.+?);

**Comment by dbsupport** [comment]
This issue was moved to dbsupport/dbs-reports#22
