### ISSUE TITLE
Przygotowac wersje to latwego wdrazania

### ISSUE THREAD

**Issue by lazydevelopers** [dbsupport/dbs-reports-issues#79]
Uzupelnic skrypt liquibase o zasilenei bazy do odstawowego stanu by mozna bylo postawic pelna aplikacje natychmiast.

**Comment by dbsupport** [comment]
This issue was moved to dbsupport/dbs-reports#18

**Comment by dbsupport** [comment]
This issue was moved to dbsupport/dbs-reports#19
